# Change these first
owner: durof # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees: 
  - durof

sites:
  - name: devs.today
    url: https://devs.today
  - name: Instant View Generation (@rreadbot)
    url: https://a.devs.today/example.org
  - name: Inline Search Bot
    url: https://backend.isbotdown.com/bots/isbot
    __dangerous__body_down: "\"isDown\":true"
  - name: Mention Bot
    url: https://backend.isbotdown.com/bots/mentionbot
    __dangerous__body_down: "\"isDown\":true"
  - name: Instant Read Bot
    url: https://backend.isbotdown.com/bots/rreadbot
    __dangerous__body_down: "\"isDown\":true"
  - name: Gen Face Bot
    url: https://backend.isbotdown.com/bots/genfacebot
    __dangerous__body_down: "\"isDown\":true"


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "durof"
  commitAuthorEmail: "ceo@devs.today"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
